In [1]:
import pickle as pkl
import numpy as np
import torch

In [2]:
def load(file_name):
    with open(file_name, 'rb') as f:
        loaded = pkl.load(f)
    return loaded

In [13]:
cd meta-mb-internal

/home/olivia/Documents/Teachable/babyai/meta-mb-internal


In [154]:
theirs = load('/home/olivia/Documents/Teachable/og_babyai/demos/DUMMY.pkl')

In [184]:
(len(theirs), len(ours))

(3, 15)

In [172]:
for i in range(10):
    ours = load(f'/home/olivia/Documents/Teachable/babyai/meta-mb-internal/data/'
                'DEBUG_teacherPreActionAdvice_dense_threshS0.99_threshA0.8_lr0.0001_ent0.01_currfnone_hot_1'
                f'/buffer/traj_train_level18_idx{i}.pkl')
#     print(to_text(ours.obs[0]['instr']))
    for j in range(len(ours.obs)):
        print(to_text(ours.obs[j]['instr']))

['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
['put', 'the', 'green', 'key', 'next', 'to', 'the', 'grey', 'key']
['put', 'the', 'green', 'key', 'next

FileNotFoundError: [Errno 2] No such file or directory: '/home/olivia/Documents/Teachable/babyai/meta-mb-internal/data/DEBUG_teacherPreActionAdvice_dense_threshS0.99_threshA0.8_lr0.0001_ent0.01_currfnone_hot_1/buffer/traj_train_level18_idx5.pkl'

In [191]:
# loop through
theirs = load('/home/olivia/Documents/Teachable/og_babyai/demos/DUMMY.pkl')

for i, their_traj in enumerate(theirs):
    print(i)
    ours = load(f'/home/olivia/Documents/Teachable/babyai/meta-mb-internal/data/'
                'DEBUG_teacherPreActionAdvice_dense_threshS0.99_threshA0.8_lr0.0001_ent0.01_currfnone_hot_1'
                f'/buffer/traj_train_level18_idx{i}.pkl')
    print(to_text(ours.obs[0]['instr']))
    print(ours.teacher_action[:,0])

    # actions
    their_action = np.array([t for t in their_traj[3]])
    assert np.array_equal(ours.teacher_action[:,0], their_action), (ours.teacher_action, their_action)
    
    # obs
#     print("comparing obs")
    our_obs = ours.obs
    their_obs = blosc.unpack_array(their_traj[1])
    for oo, to in zip(our_obs, their_obs):
        assert np.array_equal(oo['obs'], to), (oo['obs'].shape, to.shape)

#     print("first")
    assert np.array_equal(ours.obs[0]['obs'], their_obs[0]), (ours.obs[0]['obs'].shape, their_obs[0].shape)
    
    # instr
    their_mission_tokens = to_vocab_index(their_traj[0])
    our_mission_tokens = ours.obs[0]['instr']
    assert np.array_equal(their_mission_tokens, our_mission_tokens), (their_mission_tokens, our_mission_tokens)
    
print("all good!")

0
['put', 'the', 'yellow', 'ball', 'next', 'to', 'the', 'red', 'ball']
[2 1 2 2 2 0 2 3 2 0 2 2 4]
1
['put', 'the', 'green', 'key', 'next', 'to', 'the', 'grey', 'key']
[2 1 2 0 2 2 0 2 2 3 1 2 1 2 4]
2
['put', 'the', 'blue', 'key', 'next', 'to', 'the', 'yellow', 'key']
[0 2 2 1 2 0 2 2 0 3 0 2 2 2 2 0 2 2 4]
all good!


In [149]:
for t in theirs[:10]:
    print(t[0])

put the yellow ball next to the red ball
put the green key next to the grey key
put the blue key next to the yellow key
put the blue key next to the green key
put the blue key next to the grey box
put the purple box next to the grey box
put the blue ball next to the purple key
put the yellow ball next to the purple key
put the purple key next to the green ball
put the yellow box next to the grey box


In [76]:
def to_text(tokens):
    words = [vocab[token] for token in tokens if not token == 0]
    return words

In [82]:
for o in ours.obs:
    print(to_text(o['instr']))

['put', 'the', 'yellow', 'box', 'next', 'to', 'the', 'purple', 'box']
['put', 'the', 'yellow', 'box', 'next', 'to', 'the', 'purple', 'box']
['put', 'the', 'yellow', 'box', 'next', 'to', 'the', 'purple', 'box']
['put', 'the', 'yellow', 'box', 'next', 'to', 'the', 'purple', 'box']
['put', 'the', 'yellow', 'box', 'next', 'to', 'the', 'purple', 'box']
['put', 'the', 'yellow', 'box', 'next', 'to', 'the', 'purple', 'box']
['put', 'the', 'yellow', 'box', 'next', 'to', 'the', 'purple', 'box']
['put', 'the', 'yellow', 'box', 'next', 'to', 'the', 'purple', 'box']


In [80]:
ours.obs

[{'obs': array([[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
  
         [[0, 0, 0],
          [2, 5, 0],
          [2, 5, 0],
          [2, 5, 0],
          [2, 5, 0],
          [2, 5, 0],
          [2, 5, 0]],
  
         [[0, 0, 0],
          [2, 5, 0],
          [1, 0, 0],
          [6, 1, 0],
          [1, 0, 0],
          [1, 0, 0],
          [1, 0, 0]],
  
         [[0, 0, 0],
          [2, 5, 0],
          [1, 0, 0],
          [1, 0, 0],
          [1, 0, 0],
          [1, 0, 0],
          [1, 0, 0]],
  
         [[0, 0, 0],
          [2, 5, 0],
          [1, 0, 0],
          [1, 0, 0],
          [7, 4, 0],
          [1, 0, 0],
          [1, 0, 0]],
  
         [[0, 0, 0],
          [2, 5, 0],
          [1, 0, 0],
          [1, 0, 0],
          [5, 3, 0],
          [1, 0, 0],
          [1, 0, 0]],
  
         [[0, 0, 0],
          [2, 5, 0],
          [1, 0, 0],
          [6, 5, 0],
   

In [75]:
colors = ['red', 'green', 'blue', 'purple', 'yellow', 'grey']
types = ['door', 'key', 'ball', 'box']
actions = ["go", "pick", "up", "open", "put"]
fillers = ["to", "next", "the", "a"]
misc = ["follow_teacher"]
vocab = ['PAD'] + colors + types + actions + fillers + misc

In [58]:
for oo, to in zip(our_obs, their_obs):
    print("yep")
    assert np.array_equal(oo, to)

yep
yep
yep
yep
yep
yep


In [47]:
mission_tokens = to_vocab_index(theirs[0][0])

In [48]:
mission_tokens

[11, 16, 18, 1, 9, 0, 0, 0, 0, 0]

In [57]:
ours.obs[0]['instr']

[11, 16, 18, 1, 9, 0, 0, 0, 0, 0]

In [56]:
ours = load(f'/home/olivia/Documents/Teachable/babyai/meta-mb-internal/data/'
                'DEBUG_teacherPreActionAdvice_dense_threshS0.99_threshA0.8_lr0.0001_ent0.01_currfnone_hot_1'
                f'/buffer/traj_val_level0_idx0.pkl')
print(to_text(o['instr']))

array([[2],
       [2],
       [2],
       [1],
       [2],
       [2]], dtype=int32)

In [37]:
import blosc

In [46]:
def theirs_to_ours(batch):
    # Obs
    obs = blosc.unpack_array(batch[1]).tolist()
    instr = np.zeros(10))
    
    extra = ''
    pre_action_advice = np.array((len(batch[3]), 7))
    pre_action_advice[:, batch[3]]
    observations = []
    for o, i, e, p in zip(obs, instr, pre_action_advice):
        obs_dict = {
            'obs': o,
            'instr': i,
            'PreActionAdvice': p,}
        observations.append(obs_dict)
    
    # Action, teacher_action
    action = torch.IntTensor(batch[3])
    teacher_action = torch.IntTensor(batch[3])
    # Full_done
    full_done = torch.zeros_like(action)
    full_done[-1]
    our_dict = {
        'obs': observations,
        'action': action,
        'teacher_action': teacher_action,
        'full_done': full_done,
    }
    

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 24)

In [44]:
def to_vocab_index(mission, pad_length=10):
    words = mission.split(" ")
    
    mission_list = [vocab.index(word) for word in words]
    if pad_length is not None:
        mission_list = mission_list + [0] * (pad_length - len(mission_list))
    if len(mission_list) > pad_length:
        raise ValueError("Mission is too long: " + mission + str(pad_length))
    return mission_list